name: Tests

on: [push, workflow_dispatch]

jobs:
  get-go-version:
    name: Determine Go toolchain version
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine Go version
        id: get-go-version
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "{go-version}={$(cat .go-version)}" >> $GITHUB_OUTPUT

  fmtcheck:
    name: format check
    runs-on: ubuntu-latest
    needs: [get-go-version]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: 'exit $(( $(gofmt -s -l . | wc -l) != 0 ))'

  test:
    name: codec test
    runs-on: ubuntu-latest
    needs: [get-go-version]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: go test -v ./codec